
networks:
  gift.net:
    driver: bridge

services:
  app:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - "7777:80"
    volumes :
      - ./gift.appli/:/var/php
      - ./images/img:/var/php/public/img
    working_dir: /var/php/src
    networks:
      - gift.net
    depends_on:
      - sql
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"


#############################
# mysql + adminer / can be replaced by mariadb
#############################
  sql:
    image: mariadb:latest
    env_file:
      - .database_env
    ports:
      - "3306:3306"
    networks:
      gift.net:
        aliases:
          - sql.db

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - gift.net

